server:
  port: 8004
spring:
  application:
    name: hadoop-service-hdfs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: provider-service
    prefer-ip-address: true

zookeeper:
  connection: 192.168.74.153:2181,192.168.74.154:2181,192.168.74.155:2181
  timeout: 2000

info:
  app.name: hadoop-service-hdfs
  cpmpany.name: geninfo
  build.artifactId: $project.artifactId$
  build.version: $project.version$