server: 
  port: 3344 
  
spring:
  application:
    name:  hadoop_service_config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:wychenzhou/hadoop_service_config.git
 

